name: flutter_application_id
description: A package which simplifies the task of updating your Flutter app's id.
<<<<<<< HEAD
version: 0.0.3
=======
version: 0.0.6
>>>>>>> CD-test
maintainer: Charly Caulet
homepage: https://gitlab.com/uprefer/flutter/flutter_application_id
authors: 
- Charly Caulet <contact@charly-caulet.net>

dependencies: 
  args: "^1.5.0"
  yaml: "^2.1.15"
  equatable: ^1.0.1

environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  matcher: "^0.12.5"