name: flutter_application_id
description: A package which simplifies the task of updating your Flutter app's id.
version: 0.0.1
maintainer: Charly Caulet
homepage: https://gitlab.com/uprefer/flutter/flutter_application_id
authors: 
- Charly Caulet <contact@charly-caulet.net>

dependencies: 
  args: "^1.5.0"
  yaml: "^2.1.15"

environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  test: '^1.6.3'
